sudo: false
language: go
go_import_path: github.com/uber/athenadriver

env:
  global:
    - GO111MODULE=on

matrix:
  include:
  - go: 1.12.x
  - go: 1.13.x
  - go: 1.14.x
  - go: 1.15.x
  - go: 1.16.x
    env: LINT=1

install:
  - make install

script:
  - test -z "$LINT" || make lint
  - make test

after_success:
  - make cover
  - bash <(curl -s https://codecov.io/bash)
